---
apiVersion: "ember-csi.io/v1alpha1"
kind: "EmberCSI"
metadata:
  name: "my-3par"
spec:
  config:
    envVars:
      X_CSI_EMBER_CONFIG:             '{"plugin_name": "my-3par"}'
      X_CSI_PERSISTENCE_CONFIG:       '{"storage":"crd"}'
      X_CSI_BACKEND_CONFIG :          '{"name":"3par", "driver":"HPE3PARISCSI", "san_ip":"1.2.3.4", "hpe3par_api_url": "https://w.x.y.z:8080/api/v1", "hpe3par_username": "user", "hpe3par_password": "toomanysecrets", "hpe3par_cpg": "CPG_name", "san_ip": "w.x.y.z", "san_login": "user", "san_password": "toomanysecrets",  "hpe3par_iscsi_ips": "w.x.y2.z2,w.x.y2.z3,w.x.y2.z4,w.x.y2.z4", "hpe3par_debug": false, "hpe3par_iscsi_chap_enabled": false, "hpe3par_snapshot_retention": 0, "hpe3par_snapshot_expiration": 1, "use_multipath_for_image_xfer": true }'
